# Service
apiVersion: v1
kind: Service
metadata:
  name: cb-broker-service
  namespace: test1
spec:
  selector:
    app: nginxdemos
  ports:
  - name: http
    port: 80
  type: LoadBalancer
  externalTrafficPolicy: Local